### ISSUE TITLE
Could not load type 'Prometheus.Advanced.Collector` after update to Prometheus-net 3

### ISSUE THREAD

**Issue by musukvl** [bluekiri/bluekiri-diagnostics-prometheus#10]
```
public static void Main(string[] args)
{
        DiagnosticListener.AllListeners
                .SubscribeDiagnosticListener(o =>
                {
                    o.AddAspNetCoreObserver();
                    o.AddHttpHandlerObserver();
                });
```
fails with 

```
System.TypeLoadException
  HResult=0x80131522
  Message=Could not load type 'Prometheus.Advanced.Collector`1' from assembly 'Prometheus.NetStandard, Version=3.0.0.0, Culture=neutral, PublicKeyToken=a243e9817ba9d559'.
  Source=Bluekiri.Diagnostics.Prometheus
  StackTrace:
   at Bluekiri.Diagnostics.Prometheus.HttpHandlerDiagnosticListenerObserver..ctor(HttpHandlerObserverConfig config, Collector`1 counter, Collector`1 summary)
   at Bluekiri.Diagnostics.Prometheus.SubscribeOptionsExtensions.AddHttpHandlerObserver(SubscribeOptions o, Action`1 configure)
   at Application.WebApi.Program.<>c.<Main>b__0_0(SubscribeOptions o) in \Program.cs:line 16
```

**Comment by xordi** [comment]
Hi @musukvl, 

Sorry for the delay answering this. Currently the library will require some refactorings to be used with prometheus-net 3.X. There are breaking changes that will force us to rethink some code. We are also pending of this issue https://github.com/prometheus-net/prometheus-net/issues/136 in order to be able to code the unit tests properly.

If in your use case you only require ASP.NET Core metrics, I would recommend you to directly use prometheus-net 3.X with the metrics middleware.
